### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by joker234** [cytoscape/wineandcheesemap#1]
Is there a LICENSE file or information how and if I can reuse the code for my project. I missed that in other examples from http://js.cytoscape.org/ too.

**Comment by joker234** [comment]
Maybe @maxkfranz has an opinion on that issue.

**Comment by gbader** [comment]
Let's consider all demos to have the same license (MIT) as cytoscape.js  We should include a LICENSE file in all demos to be explicit about this.  So feel free to reuse the code for your project.

**Comment by joker234** [comment]
Thanks for the clarification. For further issues with other people a LICENSE file would be helpful, yes.

**Comment by maxkfranz** [comment]
The demos are all packaged in the cyjs repo in the `unstable` branch for a future release, so in future they would more clearly fall under the included `LICENSE` file in the main repo.

Sorry for the delayed response.  My account somehow wasn't set to watch this repo.
