### ISSUE TITLE
JSON node position

### ISSUE THREAD

**Issue by RK-Veltec** [cytoscape/wineandcheesemap#2]
Hello there. I'm trying to adapt the Wine and Cheese demo for a different application.
What I want to know is how I can proper position the nodes. How were the values of the original json generated? It was using Cytoscape desktop? 

The difference between how my app works is that I'm trying to plot a structure that's more a tree than a graph, so its tricky to place the nodes on the canvas.

**Comment by babycannotsay** [comment]
hi, how did you finally generate the position?

**Comment by babycannotsay** [comment]
@maxkfranz [data.json](https://gist.githubusercontent.com/maxkfranz/3d4d3c8eb808bd95bae7/raw)
how are the elements->nodes->position generated here？

**Comment by RK-Veltec** [comment]
I believe they were adjusted using [Cytoscape](https://cytoscape.org/) desktop, @babycannotsay

**Comment by babycannotsay** [comment]
thanks for you

**Comment by gbader** [comment]
Yes, I can confirm that the wine and cheese network was constructed with a mix of automated and manual layout in the Cytoscape desktop application and then exported to work with cytoscape.js.
