### ISSUE TITLE
Edges not clickable?

### ISSUE THREAD

**Issue by ayahea** [cytoscape/wineandcheesemap#29]
Although the nodes are selectable, and although `allEdges.selectable();` returns `True`, I am unable to get the edges to be clicked. Any idea on what needs to be changed to make the edges clickable?

For reference, I forked this demo into [this repo](https://github.com/ayahea/faceted-network-graph) and you can see the Pages deployment [here](https://ayahea.github.io/faceted-network-graph/). 

I have tried various functions to get the edges to be clickable, including:

```
cy.on('select unselect', 'edge', _.debounce(function (e) {
      var edge = cy.$('edge:selected');
      console.log(edge.selectable());
}, 100));
```
and:
```
cy.on('tap', 'edge', function(e){
   console.log('edge tapped');
});
```
However, neither of these functions are ever entered when the code is running. I also have a line in my stylesheet file to change the color of an edge when it is selected:
```
edge:selected {
	line-color: #4287F5; /*3/13/23 - this doesn't do anything :( */
}
```
but again, nothing. 

I realize my forked version is pretty different from the original, but the original also seems to have this problem, too. Any help on how to make the edges clickable would be much appreciated.

**Comment by maxkfranz** [comment]
See:

https://github.com/cytoscape/wineandcheesemap/blob/bdd4386890deee82430aa89be61d030c02cd56ce/src/client/cy-conf/style.js#L14

See also:

- [Events](https://js.cytoscape.org/#events)
- [Stylesheet Events](https://js.cytoscape.org/#style/events)
- [Collection Events](https://js.cytoscape.org/#collection/events)
